// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAppPassport.DataBase;

#nullable disable

namespace WebAppPassport.Migrations
{
    [DbContext(typeof(WebAppPassport.DataBase.AppContext))]
    [Migration("20260419182929_Migration_5")]
    partial class Migration_5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountryUser", b =>
                {
                    b.Property<Guid>("CountriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("CountriesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("CountryUser");
                });

            modelBuilder.Entity("PassportUser", b =>
                {
                    b.Property<Guid>("PassportsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("PassportsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PassportUser");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("DualCitizenshipAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("IsoShortCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("PassportValidityRequirementInSeconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsoShortCode")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Passport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("IsoShortCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.HasIndex("IsoShortCode")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.PassportCountryVisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToCountryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsingPassportId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisaType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToCountryId");

                    b.HasIndex("UsingPassportId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotherlandIso")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CountryUser", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Country", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppPassport.DataBase.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PassportUser", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Passport", null)
                        .WithMany()
                        .HasForeignKey("PassportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppPassport.DataBase.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Passport", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Country", "Country")
                        .WithOne("Passport")
                        .HasForeignKey("WebAppPassport.DataBase.Models.Passport", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.PassportCountryVisa", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Country", "Country")
                        .WithMany("PassportCountryVisas")
                        .HasForeignKey("ToCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppPassport.DataBase.Models.Passport", "Passport")
                        .WithMany("PassportCountryVisas")
                        .HasForeignKey("UsingPassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Country", b =>
                {
                    b.Navigation("Passport");

                    b.Navigation("PassportCountryVisas");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Passport", b =>
                {
                    b.Navigation("PassportCountryVisas");
                });
#pragma warning restore 612, 618
        }
    }
}
