// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAppPassport.DataBase;

#nullable disable

namespace WebAppPassport.Migrations
{
    [DbContext(typeof(WebAppPassport.DataBase.AppContext))]
    [Migration("20260418150429_Migration_1")]
    partial class Migration_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("DualCitizenshipAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("IsoShortCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PassportId")
                        .HasColumnType("uuid");

                    b.Property<long?>("PassportValidityRequirementInSeconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Passport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IsoShortCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.PassportCountryVisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToCountryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsingPassportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisaRegimeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisaRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToCountryId");

                    b.HasIndex("UsingPassportId");

                    b.HasIndex("VisaRuleId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotherlandIso")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.UserCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCountries");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.UserPassport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PassportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassportId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPassports");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.VisaRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.ToTable("VisaRules");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Passport", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Country", "Country")
                        .WithOne("Passport")
                        .HasForeignKey("WebAppPassport.DataBase.Models.Passport", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.PassportCountryVisa", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Country", "Country")
                        .WithMany("PassportCountryVisas")
                        .HasForeignKey("ToCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppPassport.DataBase.Models.Passport", "Passport")
                        .WithMany("PassportCountryVisas")
                        .HasForeignKey("UsingPassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppPassport.DataBase.Models.VisaRule", "VisaRule")
                        .WithMany("Destinations")
                        .HasForeignKey("VisaRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Passport");

                    b.Navigation("VisaRule");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.UserCountry", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Country", "Country")
                        .WithMany("UserCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppPassport.DataBase.Models.User", "User")
                        .WithMany("UserCountries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.UserPassport", b =>
                {
                    b.HasOne("WebAppPassport.DataBase.Models.Passport", "Passport")
                        .WithMany("UserPassports")
                        .HasForeignKey("PassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppPassport.DataBase.Models.User", "User")
                        .WithMany("UserPassports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Country", b =>
                {
                    b.Navigation("Passport")
                        .IsRequired();

                    b.Navigation("PassportCountryVisas");

                    b.Navigation("UserCountries");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.Passport", b =>
                {
                    b.Navigation("PassportCountryVisas");

                    b.Navigation("UserPassports");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.User", b =>
                {
                    b.Navigation("UserCountries");

                    b.Navigation("UserPassports");
                });

            modelBuilder.Entity("WebAppPassport.DataBase.Models.VisaRule", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
